#!/bin/sh

PKGNAME='ocs-store'
PKGVER='3.3.1'
PKGREL='1'

UPDINFO='zsync|http://dl.opendesktop.org/api/files/download/id/1532435039/as/latest/ocs-store-x86_64.AppImage.zsync'

curl -fsSL -o appimagetool https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
chmod 755 appimagetool
./appimagetool --appimage-extract

make
make DESTDIR="${PKGNAME}.AppDir" prefix=/usr install

install -D -m 755 /usr/lib/x86_64-linux-gnu/libgconf-2.so.4 ${PKGNAME}.AppDir/usr/lib/ocs-store-linux-x64/libgconf-2.so.4
install -D -m 755 /usr/lib/x86_64-linux-gnu/libXss.so.1 ${PKGNAME}.AppDir/usr/lib/ocs-store-linux-x64/libXss.so.1
install -D -m 755 /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libcanberra-gtk-module.so ${PKGNAME}.AppDir/usr/lib/ocs-store-linux-x64/libcanberra-gtk-module.so
install -D -m 755 /usr/lib/x86_64-linux-gnu/libgnome-keyring.so.0 ${PKGNAME}.AppDir/usr/lib/ocs-store-linux-x64/libgnome-keyring.so.0

install -D -m 755 ${PKGNAME}.AppDir/usr/bin/${PKGNAME} ${PKGNAME}.AppDir/AppRun
install -D -m 644 ${PKGNAME}.AppDir/usr/share/applications/${PKGNAME}.desktop ${PKGNAME}.AppDir/${PKGNAME}.desktop
install -D -m 644 ${PKGNAME}.AppDir/usr/share/icons/hicolor/scalable/apps/${PKGNAME}.svg ${PKGNAME}.AppDir/${PKGNAME}.svg

./squashfs-root/AppRun -u "${UPDINFO}" ${PKGNAME}.AppDir

mv *-x86_64.AppImage ${PKGNAME}-${PKGVER}-${PKGREL}-x86_64.AppImage
